### ISSUE TITLE
Write error messages to stderr rather than stdout?

### ISSUE THREAD

**Issue by swofford** [stamatak/standard-RAxML#21]
I was just wondering if there is a reason that RAxML does not write its error messages to *stderr* rather than to *stdout*.  I want to run it from programs and scripts where capturing error output separately from normal output is desirable.

Unless there's a good reason for not writing error messages to *stderr*, consider this as a suggestion.  I can fork a copy and do it for you if you would be likely to accept my changes--please let me know what you think.

Dave Swofford

**Comment by stamatak** [comment]
Dear Dave,

Feel free to and thanks for pointing this out. I don't know though if it 
is worth the effort since RAxML urgently needs a re-design anyway.

All the best,

Alexis

On 19.01.2016 03:00, David Swofford wrote:
> I was just wondering if there is a reason that RAxML does not write its
> error messages to /stderr/ rather than to /stdout/ I want to run it from
> programs and scripts where capturing error output separately from normal
> output is desirable
>
> Unless there's a good reason for not writing error messages to /stderr/,
> consider this as a suggestion I can fork a copy and do it for you if you
> would be likely to accept my changes--please let me know what you think
>
> Dave Swofford
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamatak/standard-RAxML/issues/21>.
>

-- 
Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org
